<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt" xml:lang="pt"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Elton Jorge">

<title>Relatorio Geral das lojas do grupo Alurastore</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="relatorio_files/libs/clipboard/clipboard.min.js"></script>
<script src="relatorio_files/libs/quarto-html/quarto.js"></script>
<script src="relatorio_files/libs/quarto-html/popper.min.js"></script>
<script src="relatorio_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="relatorio_files/libs/quarto-html/anchor.min.js"></script>
<link href="relatorio_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="relatorio_files/libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="relatorio_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="relatorio_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="relatorio_files/libs/bootstrap/bootstrap-8a79a254b8e706d3c925cde0a310d4f0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Relatorio Geral das lojas do grupo Alurastore</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor</div>
    <div class="quarto-title-meta-contents">
             <p>Elton Jorge </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Data de Publicação</div>
    <div class="quarto-title-meta-contents">
      <p class="date">10 de maio de 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introdução" class="level1">
<h1><strong><em>Introdução</em></strong></h1>
<p>Este relatório tem como objetivo principal fornecer suporte aos stakeholders na tomada de decisões mais assertivas e estratégicas para suas empresas. Através da aplicação de técnicas de ciência e análise de dados, são apresentadas recomendações fundamentadas em evidências sólidas, com foco na otimização de resultados e no direcionamento estratégico baseado em dados concretos.</p>
<p>As análises aqui detalhadas foram construídas a partir dos dados operacionais das quatro unidades pertencentes ao grupo <em>AluraStore</em> de propriedade do Sr.&nbsp;João. O foco está em indicadores-chave de desempenho, oferecendo uma visão ampla e comparativa do funcionamento das lojas.</p>
<p>Foram considerados diversos aspectos relevantes, como faturamento, volume de vendas, custos com frete, produtos mais vendidos e a localização geográfica dos clientes. Esses elementos fornecem insights valiosos, permitindo uma compreensão mais aprofundada do posicionamento de cada loja no mercado, além de auxiliar na identificação de oportunidades de melhoria e crescimento.</p>
<section id="bibliotecas" class="level5">
<h5 class="anchored" data-anchor-id="bibliotecas"><em>Bibliotecas</em></h5>
</section>
<section id="importação-dos-dados" class="level5">
<h5 class="anchored" data-anchor-id="importação-dos-dados"><em>importação dos dados</em></h5>
</section>
<section id="análise-do-faturamento" class="level3">
<h3 class="anchored" data-anchor-id="análise-do-faturamento"><strong><em>Análise do faturamento</em></strong></h3>
<div id="c4f0aba5" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">loja</th>
<th data-quarto-table-cell-role="th">Preço</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>loja 1</td>
<td>R$1.534.509,12</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>loja 2</td>
<td>R$1.488.459,06</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>loja 3</td>
<td>R$1.464.025,03</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>loja 4</td>
<td>R$1.384.497,58</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>O grupo do <em>AluraStore de propriedade do sr.João,</em> faturou no período analisado, um total de R$ 5.871.490,79 (cinco milhões, oitocentos e setenta e um mil, quatrocentos e noventa reais e setenta e nove centavos). Desse montante, a Loja 1 foi responsável por 26,1%, demonstrando um desempenho relevante dentro do conjunto das unidades.</p>
<p>De maneira geral, observa-se que o faturamento das quatro lojas é relativamente equilibrado, com valores próximos entre si. No entanto, a Loja 1 se destacou como a mais eficiente, liderando em faturamento e contribuindo significativamente para o resultado total do grupo. Por outro lado, a Loja 4 apresentou desempenho inferior em comparação às demais, registrando o menor faturamento entre todas as unidades.</p>
<div id="b9c029b3" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="relatorio_files/figure-html/cell-5-output-1.png" width="661" height="469" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="f42a3a62" class="cell" data-execution_count="5">
<div class="cell-output cell-output-stdout">
<pre><code> O total do faturamento do seu João, com as 4 lojas foi de: R$ 5.871.490,79</code></pre>
</div>
</div>
<div id="f2a228df" class="cell" data-execution_count="6">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="relatorio_files/figure-html/cell-7-output-1.png" width="540" height="410" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<section id="análise-do-faturamento-anual" class="level4">
<h4 class="anchored" data-anchor-id="análise-do-faturamento-anual"><em>Análise do faturamento Anual</em></h4>
<div id="17daf4d4" class="cell" data-execution_count="7">
<div class="cell-output cell-output-stdout">
<pre><code>Ano
2020    R$1.789.272,37
2021    R$1.898.820,98
2022    R$1.769.933,73
2023      R$413.463,71
Name: Preço, dtype: object</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>C:\Users\ELTON\AppData\Local\Temp\ipykernel_12720\2311554652.py:1: UserWarning:

Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
</code></pre>
</div>
</div>
<div id="edc9efe5" class="cell" data-execution_count="8">
<div class="cell-output cell-output-stdout">
<pre><code>loja        loja 1        loja 2        loja 3        loja 4
Ano                                                         
2020  R$491.911,51  R$427.288,25  R$428.943,09  R$441.129,52
2021  R$482.829,91  R$468.288,89  R$483.938,91  R$463.763,27
2022  R$422.086,24  R$477.635,56  R$467.250,70  R$402.961,23
2023  R$137.681,46  R$115.246,36   R$83.892,33   R$76.643,56</code></pre>
</div>
</div>
<p>Com base na análise histórica do faturamento anual, constata-se que a Loja 4, de forma consistente, obteve os menores valores de receita na maioria dos anos observados, o que reforça a necessidade de uma avaliação mais aprofundada sobre suas operações, estratégias de vendas e posicionamento no mercado.</p>
</section>
</section>
<section id="vendas-por-categoria" class="level3">
<h3 class="anchored" data-anchor-id="vendas-por-categoria"><strong><em>Vendas por categoria</em></strong></h3>
<p>O grupo <em>AluraStore</em> tem se destacado pela diversidade de categorias de produtos comercializados. Entre essas categorias, três se sobressaem no volume de vendas, ocupando o Top 3 em unidades vendidas: móveis, com 1.886 unidades; eletrônicos, com 1.772 unidades; e brinquedos, com 1.290 unidades.</p>
<p>No entanto, ao analisarmos o faturamento por categoria, observa-se uma leve mudança nesse ranking. Os três segmentos que mais geram receita para o grupo são: eletrônicos, com R$ 2.214.099,72; eletrodomésticos, com R$ 1.766.337,03; e móveis, com R$ 1.010.214,00. Apesar de figurar entre os mais vendidos, a categoria de brinquedos ocupa apenas a 6ª posição em faturamento, reflexo de seu baixo preço médio por unidade.</p>
<div id="38879588" class="cell" data-execution_count="9">
<div class="cell-output cell-output-stdout">
<pre><code>Quantidade vendida por categoria:

Categoria do Produto
moveis                   1886
eletronicos              1772
brinquedos               1290
eletrodomesticos         1149
esporte e lazer          1113
instrumentos musicais     753
livros                    742
utilidades domesticas     730
Name: count, dtype: int64

Faturamento por categoria:

Categoria do Produto
brinquedos                  R$98.140,86
eletrodomesticos         R$1.766.337,03
eletronicos              R$2.214.099,72
esporte e lazer            R$190.635,39
instrumentos musicais      R$465.029,67
livros                      R$50.260,74
moveis                   R$1.010.214,00
utilidades domesticas       R$76.773,38
Name: Preço, dtype: object</code></pre>
</div>
</div>
<div id="a6754284" class="cell" data-execution_count="10">
<div class="cell-output cell-output-stdout">
<pre><code>
Resumo por categoria:

                       Quantidade Vendida Preço Médio(R$) Faturamento(R$)  \
Categoria do Produto                                                        
eletronicos                          1772      R$1.249,49  R$2.214.099,72   
eletrodomesticos                     1149      R$1.537,28  R$1.766.337,03   
moveis                               1886        R$535,64  R$1.010.214,00   
instrumentos musicais                 753        R$617,57    R$465.029,67   
esporte e lazer                      1113        R$171,28    R$190.635,39   
brinquedos                           1290         R$76,08     R$98.140,86   
utilidades domesticas                 730        R$105,17     R$76.773,38   
livros                                742         R$67,74     R$50.260,74   

                      % Faturamento  
Categoria do Produto                 
eletronicos                  37.71%  
eletrodomesticos             30.08%  
moveis                       17.21%  
instrumentos musicais         7.92%  
esporte e lazer               3.25%  
brinquedos                    1.67%  
utilidades domesticas         1.31%  
livros                        0.86%  </code></pre>
</div>
</div>
<div id="b1ea00ee" class="cell" data-execution_count="11">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="relatorio_files/figure-html/cell-12-output-1.png" width="661" height="469" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>As quatro unidades do grupo apresentam o mesmo padrão em relação à comercialização de produtos. Não há variações no ranking de vendas por categoria entre as lojas, o que evidencia uma padronização no perfil de consumo e na estratégia de vendas adotada pelo grupo. As diferenças entre as unidades se concentram apenas nas quantidades vendidas e nos preços médios praticados.</p>
<div id="e6177ed7" class="cell" data-execution_count="12">
<div class="cell-output cell-output-stdout">
<pre><code>
Resumo da LOJA 1
                       Quantidade Vendida Preço Médio(R$) Faturamento(R$)  \
Categoria do Produto                                                        
eletronicos                           448      R$1.278,26    R$572.659,23   
eletrodomesticos                      312      R$1.554,21    R$484.913,36   
moveis                                465        R$538,02    R$250.178,11   
instrumentos musicais                 182        R$668,86    R$121.731,69   
esporte e lazer                       284        R$184,46     R$52.387,55   
brinquedos                            324         R$74,05     R$23.993,78   
utilidades domesticas                 171         R$99,01     R$16.931,48   
livros                                173         R$67,71     R$11.713,92   

                      % Faturamento  
Categoria do Produto                 
eletronicos                  37.32%  
eletrodomesticos             31.60%  
moveis                       16.30%  
instrumentos musicais         7.93%  
esporte e lazer               3.41%  
brinquedos                    1.56%  
utilidades domesticas         1.10%  
livros                        0.76%  

Resumo da LOJA 2
                       Quantidade Vendida Preço Médio(R$) Faturamento(R$)  \
Categoria do Produto                                                        
eletronicos                           422      R$1.298,04    R$547.773,71   
eletrodomesticos                      305      R$1.523,80    R$464.758,13   
moveis                                442        R$532,21    R$235.234,68   
instrumentos musicais                 224        R$624,94    R$139.987,03   
esporte e lazer                       275        R$168,46     R$46.326,09   
brinquedos                            313         R$67,93     R$21.262,21   
utilidades domesticas                 181        R$108,63     R$19.662,86   
livros                                197         R$68,30     R$13.454,35   

                      % Faturamento  
Categoria do Produto                 
eletronicos                  36.80%  
eletrodomesticos             31.22%  
moveis                       15.80%  
instrumentos musicais         9.40%  
esporte e lazer               3.11%  
brinquedos                    1.43%  
utilidades domesticas         1.32%  
livros                        0.90%  

Resumo da LOJA 3
                       Quantidade Vendida Preço Médio(R$) Faturamento(R$)  \
Categoria do Produto                                                        
eletronicos                           451      R$1.214,41    R$547.699,92   
eletrodomesticos                      278      R$1.579,08    R$438.984,89   
moveis                                499        R$537,27    R$268.095,56   
instrumentos musicais                 177        R$582,91    R$103.174,45   
esporte e lazer                       277        R$171,32     R$47.456,10   
brinquedos                            315         R$82,12     R$25.869,20   
utilidades domesticas                 177        R$113,45     R$20.080,21   
livros                                185         R$68,46     R$12.664,70   

                      % Faturamento  
Categoria do Produto                 
eletronicos                  37.41%  
eletrodomesticos             29.98%  
moveis                       18.31%  
instrumentos musicais         7.05%  
esporte e lazer               3.24%  
brinquedos                    1.77%  
utilidades domesticas         1.37%  
livros                        0.87%  

Resumo da LOJA 4
                       Quantidade Vendida Preço Médio(R$) Faturamento(R$)  \
Categoria do Produto                                                        
eletronicos                           451      R$1.210,57    R$545.966,86   
eletrodomesticos                      254      R$1.486,93    R$377.680,65   
moveis                                480        R$534,80    R$256.705,65   
instrumentos musicais                 170        R$589,04    R$100.136,50   
esporte e lazer                       277        R$160,53     R$44.465,65   
brinquedos                            338         R$79,93     R$27.015,67   
utilidades domesticas                 201         R$99,99     R$20.098,83   
livros                                187         R$66,46     R$12.427,77   

                      % Faturamento  
Categoria do Produto                 
eletronicos                  39.43%  
eletrodomesticos             27.28%  
moveis                       18.54%  
instrumentos musicais         7.23%  
esporte e lazer               3.21%  
brinquedos                    1.95%  
utilidades domesticas         1.45%  
livros                        0.90%  </code></pre>
</div>
</div>
</section>
<section id="média-de-avaliação-das-lojas" class="level3">
<h3 class="anchored" data-anchor-id="média-de-avaliação-das-lojas"><strong><em>Média de Avaliação das Lojas</em></strong></h3>
<p>A média geral de avaliação do grupo <em>AluraStore</em> é de 4,01. As quatro unidades apresentam médias de avaliação muito próximas entre si, demonstrando um padrão consistente de atendimento e qualidade percebida pelos clientes. As Lojas 2 e 3 lideram o ranking de avaliação, enquanto a Loja 1 apresenta a menor média. No entanto, a diferença entre a melhor e a pior avaliação é mínima, de apenas 0,07 ponto.</p>
<div id="877778e5" class="cell" data-execution_count="13">
<div class="cell-output cell-output-stdout">
<pre><code>
A média de avaliações das 4 lojas somadas é:

4.01</code></pre>
</div>
</div>
<div id="4d15df5f" class="cell" data-execution_count="14">
<div class="cell-output cell-output-stdout">
<pre><code>loja 1: 3.98
loja 2: 4.04
loja 3: 4.05
loja 4: 4.00</code></pre>
</div>
</div>
<div id="d468dc9b" class="cell" data-execution_count="15">
<div class="cell-output cell-output-stdout">
<pre><code>Loja: loja 1:| avaliação: 1| quantidade: 319
Loja: loja 1:| avaliação: 2| quantidade: 86
Loja: loja 1:| avaliação: 3| quantidade: 218
Loja: loja 1:| avaliação: 4| quantidade: 444
Loja: loja 1:| avaliação: 5| quantidade: 1292

Loja: loja 2:| avaliação: 1| quantidade: 273
Loja: loja 2:| avaliação: 2| quantidade: 93
Loja: loja 2:| avaliação: 3| quantidade: 209
Loja: loja 2:| avaliação: 4| quantidade: 482
Loja: loja 2:| avaliação: 5| quantidade: 1302

Loja: loja 3:| avaliação: 1| quantidade: 297
Loja: loja 3:| avaliação: 2| quantidade: 79
Loja: loja 3:| avaliação: 3| quantidade: 193
Loja: loja 3:| avaliação: 4| quantidade: 434
Loja: loja 3:| avaliação: 5| quantidade: 1356

Loja: loja 4:| avaliação: 1| quantidade: 310
Loja: loja 4:| avaliação: 2| quantidade: 85
Loja: loja 4:| avaliação: 3| quantidade: 210
Loja: loja 4:| avaliação: 4| quantidade: 453
Loja: loja 4:| avaliação: 5| quantidade: 1300</code></pre>
</div>
</div>
<div id="c7e45f05" class="cell" data-execution_count="17">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="relatorio_files/figure-html/cell-18-output-1.png" width="1141" height="566" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="produtos-mais-e-menos-vendidos" class="level3">
<h3 class="anchored" data-anchor-id="produtos-mais-e-menos-vendidos"><strong><em>Produtos Mais e Menos Vendidos</em></strong></h3>
<p>A <em>AluraStore</em> tem como marca registrada a ampla diversificação de seus produtos. De brinquedos infantis a eletrônicos avançados, passando por utensílios de cozinha e instrumentos musicais, é possível encontrar uma grande variedade de itens nas unidades da <em>AluraStore</em>. Essa diversidade oferece ao cliente a conveniência de adquirir produtos de diferentes segmentos em um único lugar, com preços acessíveis e competitivos no mercado.</p>
<p>O Top 5 dos produtos mais vendidos inclui: cômoda (210 unidades), carrinho de controle remoto e micro-ondas (ambos com 206 unidades), bateria (203 unidades) e cama king (201 unidades).</p>
<div id="bcb1c110" class="cell" data-execution_count="18">
<div class="cell-output cell-output-display" data-execution_count="18">
<pre><code>Produto
Cômoda                      210
Micro-ondas                 206
Carrinho controle remoto    206
Bateria                     203
Cama king                   201
Jogo de panelas             200
Secadora de roupas          200
Modelagem preditiva         200
Cama box                    199
Blocos de montar            199
Name: count, dtype: int64</code></pre>
</div>
</div>
<p>Por outro lado, os produtos com menor volume de vendas nas unidades são: o livro ‘Ciência de Dados com Python’, guitarra, mochila, headset e o celular ABXY</p>
<div id="baf36c17" class="cell" data-execution_count="19">
<div class="cell-output cell-output-display" data-execution_count="19">
<pre><code>Produto
Smartwatch                     172
Panela de pressão              172
Jogo de copos                  169
Poltrona                       168
Assistente virtual             167
Ciência de dados com python    166
Guitarra                       165
Mochila                        163
Headset                        158
Celular ABXY                   157
Name: count, dtype: int64</code></pre>
</div>
</div>
<div id="f55fe56f" class="cell" data-execution_count="20">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="relatorio_files/figure-html/cell-21-output-1.png" width="663" height="471" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>A análise da tabela a seguir revela uma distinção importante entre volume de vendas e geração de faturamento. Os produtos mais vendidos não são, necessariamente, os que mais contribuem para a receita do grupo. Itens como o celular Plus X42, geladeiras e outros eletrodomésticos de maior valor agregado não figuram no Top 10 em número de unidades vendidas, mas aparecem entre os maiores responsáveis pelo faturamento. Esse fenômeno é explicado pelo alto preço médio desses produtos, que compensam a menor quantidade vendida, demonstrando a importância de considerar tanto a demanda quanto o ticket médio na definição de estratégias comerciais e de estoque.</p>
<div id="964297de" class="cell" data-execution_count="22">
<div class="cell-output cell-output-stdout">
<pre><code>                                                 Produto  Quantidade Vendida  \
Produto                                                                        
Cômoda                                            Cômoda                 210   
Carrinho controle remoto        Carrinho controle remoto                 206   
Micro-ondas                                  Micro-ondas                 206   
Bateria                                          Bateria                 203   
Cama king                                      Cama king                 201   
Modelagem preditiva                  Modelagem preditiva                 200   
Jogo de panelas                          Jogo de panelas                 200   
Secadora de roupas                    Secadora de roupas                 200   
Blocos de montar                        Blocos de montar                 199   
Cama box                                        Cama box                 199   
Celular Plus X42                        Celular Plus X42                 198   
Bola de basquete                        Bola de basquete                 197   
Pandeiro                                        Pandeiro                 197   
Guarda roupas                              Guarda roupas                 197   
Bicicleta                                      Bicicleta                 196   
Iniciando em programação        Iniciando em programação                 195   
Smart TV                                        Smart TV                 192   
Geladeira                                      Geladeira                 191   
Faqueiro                                        Faqueiro                 189   
Lava louças                                  Lava louças                 189   
Kit banquetas                              Kit banquetas                 188   
Violão                                            Violão                 188   
Impressora                                    Impressora                 188   
Fogão                                              Fogão                 187   
Copo térmico                                Copo térmico                 187   
TV Led UHD 4K                              TV Led UHD 4K                 187   
Corda de pular                            Corda de pular                 186   
Mesa de jantar                            Mesa de jantar                 185   
Bola de vôlei                              Bola de vôlei                 184   
Sofá retrátil                              Sofá retrátil                 182   
Dashboards com Power BI          Dashboards com Power BI                 181   
Cadeira de escritório              Cadeira de escritório                 181   
Xadrez de madeira                      Xadrez de madeira                 180   
Cubo mágico 8x8                          Cubo mágico 8x8                 180   
Tablet ABXY                                  Tablet ABXY                 179   
Lavadora de roupas                    Lavadora de roupas                 176   
Jogo de tabuleiro                      Jogo de tabuleiro                 175   
Mesa de centro                            Mesa de centro                 175   
Dinossauro Rex                            Dinossauro Rex                 175   
Boneca bebê                                  Boneca bebê                 175   
Fone de ouvido                            Fone de ouvido                 174   
Smartwatch                                    Smartwatch                 172   
Panela de pressão                      Panela de pressão                 172   
Jogo de copos                              Jogo de copos                 169   
Poltrona                                        Poltrona                 168   
Assistente virtual                    Assistente virtual                 167   
Ciência de dados com python  Ciência de dados com python                 166   
Guitarra                                        Guitarra                 165   
Mochila                                          Mochila                 163   
Headset                                          Headset                 158   
Celular ABXY                                Celular ABXY                 157   

                            Preço Médio(R$) Faturamento(R$) % do Faturamento  
Produto                                                                       
Cômoda                             R$370,92     R$77.893,20           1.327%  
Carrinho controle remoto            R$95,59     R$19.691,54           0.335%  
Micro-ondas                        R$748,87    R$154.267,22           2.627%  
Bateria                            R$970,81    R$197.074,43           3.356%  
Cama king                          R$900,70    R$181.040,70           3.083%  
Modelagem preditiva                 R$84,10     R$16.820,00           0.286%  
Jogo de panelas                    R$203,38     R$40.676,00           0.693%  
Secadora de roupas               R$1.401,59    R$280.318,00           4.774%  
Blocos de montar                    R$45,58      R$9.070,42           0.154%  
Cama box                           R$697,47    R$138.796,53           2.364%  
Celular Plus X42                 R$2.700,68    R$534.734,64           9.107%  
Bola de basquete                    R$66,05     R$13.011,85           0.222%  
Pandeiro                            R$85,71     R$16.884,87           0.288%  
Guarda roupas                      R$651,41    R$128.327,77           2.186%  
Bicicleta                          R$656,37    R$128.648,52           2.191%  
Iniciando em programação            R$65,81     R$12.832,95           0.219%  
Smart TV                         R$2.015,43    R$386.962,56           6.591%  
Geladeira                        R$2.687,17    R$513.249,47           8.741%  
Faqueiro                            R$60,39     R$11.413,71           0.194%  
Lava louças                      R$1.696,91    R$320.715,99           5.462%  
Kit banquetas                      R$377,90     R$71.045,20           1.210%  
Violão                             R$417,72     R$78.531,36           1.338%  
Impressora                         R$398,77     R$74.968,76           1.277%  
Fogão                              R$933,13    R$174.495,31           2.972%  
Copo térmico                        R$60,59     R$11.330,33           0.193%  
TV Led UHD 4K                    R$3.083,70    R$576.651,90           9.821%  
Corda de pular                      R$21,99      R$4.090,14           0.070%  
Mesa de jantar                     R$337,41     R$62.420,85           1.063%  
Bola de vôlei                       R$65,94     R$12.132,96           0.207%  
Sofá retrátil                      R$903,14    R$164.371,48           2.799%  
Dashboards com Power BI             R$47,28      R$8.557,68           0.146%  
Cadeira de escritório              R$509,02     R$92.132,62           1.569%  
Xadrez de madeira                   R$38,14      R$6.865,20           0.117%  
Cubo mágico 8x8                     R$20,21      R$3.637,80           0.062%  
Tablet ABXY                      R$1.631,38    R$292.017,02           4.973%  
Lavadora de roupas               R$1.836,89    R$323.292,64           5.506%  
Jogo de tabuleiro                  R$247,25     R$43.268,75           0.737%  
Mesa de centro                     R$227,37     R$39.789,75           0.678%  
Dinossauro Rex                      R$23,72      R$4.151,00           0.071%  
Boneca bebê                         R$65,46     R$11.455,50           0.195%  
Fone de ouvido                     R$126,56     R$22.021,44           0.375%  
Smartwatch                         R$232,01     R$39.905,72           0.680%  
Panela de pressão                  R$100,23     R$17.239,56           0.294%  
Jogo de copos                       R$44,05      R$7.444,45           0.127%  
Poltrona                           R$323,78     R$54.395,04           0.926%  
Assistente virtual                 R$275,19     R$45.956,73           0.783%  
Ciência de dados com python         R$72,58     R$12.048,28           0.205%  
Guitarra                         R$1.045,70    R$172.540,50           2.939%  
Mochila                            R$131,42     R$21.421,46           0.365%  
Headset                            R$191,97     R$30.331,26           0.517%  
Celular ABXY                     R$1.341,07    R$210.547,99           3.586%  </code></pre>
</div>
</div>
<div id="6af48a7d" class="cell" data-execution_count="23">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="relatorio_files/figure-html/cell-24-output-1.png" width="1908" height="747" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Com base nos dados analisados, constatamos que o Top 5 de produtos mais vendidos varia consideravelmente entre as unidades do grupo. As Lojas 3 e 4, em especial, apresentam um perfil de vendas focado em itens de menor valor agregado, com preços médios mais baixos em comparação ao Top 5 das Lojas 1 e 2. Essa diferença no mix de produtos vendidos influencia diretamente o desempenho financeiro dessas unidades.</p>
<p>Apesar de manterem volumes de vendas expressivos, as Lojas 3 e 4 geram menor faturamento, justamente por concentrarem suas vendas em produtos de menor ticket médio. Esse padrão evidencia a importância de estratégias personalizadas por unidade, considerando o perfil do público atendido, a localização e o potencial de valorização do portfólio de produtos em cada loja.</p>
<div id="8a9194e4" class="cell" data-execution_count="24">
<div class="cell-output cell-output-stdout">
<pre><code>
--- Tabela da LOJA 1---

&gt;&gt; Mais Vendidos:
           Produto  Quantidade_Vendida Preço_Médio  Faturamento
     TV Led UHD 4K                  60  R$3.158,90 R$189.534,28
       Micro-ondas                  60    R$772,48  R$46.348,89
     Guarda roupas                  60    R$654,71  R$39.282,78
Secadora de roupas                  58  R$1.357,75  R$78.749,73
  Blocos de montar                  56     R$44,42   R$2.487,74

&gt;&gt; Menos Vendidos
          Produto  Quantidade_Vendida Preço_Médio Faturamento
          Headset                  33    R$191,14  R$6.307,71
     Celular ABXY                  33  R$1.319,23 R$43.534,47
Panela de pressão                  35    R$100,16  R$3.505,71
         Pandeiro                  36     R$82,92  R$2.985,19
          Mochila                  39    R$132,22  R$5.156,50

--- Tabela da LOJA 2---

&gt;&gt; Mais Vendidos:
                 Produto  Quantidade_Vendida Preço_Médio Faturamento
Iniciando em programação                  65     R$64,15  R$4.169,96
             Micro-ondas                  62    R$778,33 R$48.256,37
                 Bateria                  61  R$1.009,29 R$61.566,87
                  Violão                  58    R$428,69 R$24.864,13
                Pandeiro                  58     R$85,64  R$4.967,00

&gt;&gt; Menos Vendidos
          Produto  Quantidade_Vendida Preço_Médio Faturamento
Jogo de tabuleiro                  32    R$242,17  R$7.749,58
       Impressora                  34    R$407,26 R$13.846,69
   Mesa de jantar                  34    R$338,71 R$11.516,31
         Poltrona                  35    R$320,51 R$11.218,00
   Fone de ouvido                  37    R$128,63  R$4.759,28

--- Tabela da LOJA 3---

&gt;&gt; Mais Vendidos:
        Produto  Quantidade_Vendida Preço_Médio Faturamento
  Kit banquetas                  57    R$390,63 R$22.265,96
 Mesa de jantar                  56    R$341,10 R$19.101,40
      Cama king                  56    R$924,64 R$51.779,90
         Cômoda                  55    R$372,49 R$20.487,18
Jogo de panelas                  55    R$210,82 R$11.595,04

&gt;&gt; Menos Vendidos
         Produto  Quantidade_Vendida Preço_Médio Faturamento
Blocos de montar                  35     R$47,14  R$1.649,81
         Mochila                  36    R$131,38  R$4.729,54
     Micro-ondas                  36    R$709,40 R$25.538,25
   Jogo de copos                  36     R$44,84  R$1.614,20
        Guitarra                  38  R$1.047,30 R$39.797,29

--- Tabela da LOJA 4---

&gt;&gt; Mais Vendidos:
                 Produto  Quantidade_Vendida Preço_Médio Faturamento
                Cama box                  62    R$708,53 R$43.928,57
                Faqueiro                  59     R$59,87  R$3.532,16
               Cama king                  56    R$894,16 R$50.073,16
 Dashboards com Power BI                  56     R$47,40  R$2.654,28
Carrinho controle remoto                  55     R$97,31  R$5.352,22

&gt;&gt; Menos Vendidos
           Produto  Quantidade_Vendida Preço_Médio  Faturamento
          Guitarra                  33  R$1.043,35  R$34.430,67
     Guarda roupas                  34    R$643,98  R$21.895,36
            Violão                  37    R$405,67  R$15.009,67
Lavadora de roupas                  38  R$1.840,83  R$69.951,68
         Geladeira                  38  R$2.641,12 R$100.362,59</code></pre>
</div>
</div>
</section>
<section id="frete-médio-por-loja" class="level3">
<h3 class="anchored" data-anchor-id="frete-médio-por-loja"><strong><em>Frete Médio por Loja</em></strong></h3>
<p>De maneira geral, os gastos com frete no grupo <em>AluraStore</em> demonstram um alto nível de padronização entre as quatro unidades. Cada loja destinou, em média, 5,33% do seu faturamento para despesas com frete, o que evidencia a aplicação consistente da política logística definida pelo grupo. Essa uniformidade indica um controle eficiente dos custos operacionais e o alinhamento das unidades com os princípios estratégicos da empresa.</p>
<p>No período analisado, o valor total desembolsado com fretes foi de R$ 312.930,66, distribuído de forma proporcional entre as lojas. A correlação direta entre o faturamento e os gastos com frete — ou seja, a loja que mais vende também é a que mais investe em logística — reforça a ausência de distorções ou desequilíbrios nesse aspecto. Esse cenário revela não apenas uma gestão eficiente dos custos logísticos, mas também a maturidade do grupo na aplicação de uma política operacional coerente, transparente e economicamente sustentável.</p>
<div id="ab8f41b9" class="cell" data-execution_count="25">
<div class="cell-output cell-output-stdout">
<pre><code>Total gasto com frete do grupo(4 lojas): R$312x930.66</code></pre>
</div>
</div>
<div id="dec90b5b" class="cell" data-execution_count="26">
<div class="cell-output cell-output-display" data-execution_count="26">
<pre><code>loja
loja 1    R$81.837,97
loja 2    R$79.314,16
loja 3    R$78.022,66
loja 4    R$73.755,88
Name: Frete, dtype: object</code></pre>
</div>
</div>
<div id="c0b821d8" class="cell" data-execution_count="27">
<div class="cell-output cell-output-display" data-execution_count="27">
<pre><code>loja
loja 1    R$ 34.69
loja 2    R$ 33.62
loja 3    R$ 33.07
loja 4    R$ 31.28
Name: Frete, dtype: object</code></pre>
</div>
</div>
<div id="fd5b2956" class="cell" data-execution_count="28">
<div class="cell-output cell-output-stdout">
<pre><code>       Valor Médio do Frete Frete Total(R$) % do Frete Total  \
loja                                                           
loja 1             R$ 34.69     R$81.837,97           26.15%   
loja 2             R$ 33.62     R$79.314,16           25.35%   
loja 3             R$ 33.07     R$78.022,66           24.93%   
loja 4             R$ 31.28     R$73.755,88           23.57%   

       Faturamento Total(R$) % Frete / Faturamento Lucro Bruto Estimado(R$)  
loja                                                                         
loja 1        R$1.534.509,12                 5.33%          R$ 1.452.671,15  
loja 2        R$1.488.459,06                 5.33%          R$ 1.409.144,90  
loja 3        R$1.464.025,03                 5.33%          R$ 1.386.002,37  
loja 4        R$1.384.497,58                 5.33%          R$ 1.310.741,70  </code></pre>
</div>
</div>
</section>
<section id="dados-geograficos" class="level3">
<h3 class="anchored" data-anchor-id="dados-geograficos"><strong><em>Dados geograficos</em></strong></h3>
<p>O grupo <em>AluraStore</em> possui representatividade comercial em todas as regiões do Brasil e em todos os estados, o que demonstra um alcance nacional relevante. No entanto, observa-se uma forte concentração de clientes e faturamento na região Sudeste, destacando-se como o principal mercado do grupo. Diante disso, recomenda-se a ampliação da presença nas demais regiões do país, especialmente Norte, Nordeste e Centro-Oeste, com estratégias direcionadas de marketing, logística e expansão, visando equilibrar a distribuição geográfica das vendas e explorar o potencial de crescimento em mercados ainda subexplorados.</p>
<div id="6c18cd0c" class="cell" data-execution_count="29">
<div class="cell-output cell-output-stdout">
<pre><code>AC : 3
AL : 41
AM : 14
AP : 9
BA : 310
CE : 151
DF : 242
ES : 171
GO : 186
MA : 62
MG : 1102
MS : 82
MT : 80
PA : 81
PB : 46
PE : 181
PI : 40
PR : 473
RJ : 1212
RN : 48
RO : 19
RR : 2
RS : 534
SC : 346
SE : 28
SP : 3943
TO : 29</code></pre>
</div>
</div>
<div id="1f4f7cb7" class="cell" data-execution_count="30">
<div class="cell-output cell-output-stdout">
<pre><code>Sul: 1353
Sudeste: 6428
Norte: 157
Nordeste: 907
Centro-Oeste: 590</code></pre>
</div>
</div>
<div id="bac2f89d" class="cell" data-execution_count="31">
<div class="cell-output cell-output-stdout">
<pre><code>        Sul  Sudeste  Norte  Nordeste  Centro-Oeste
loja 1  378     1585     46       206           144
loja 2  316     1613     32       230           168
loja 3  325     1620     44       230           140
loja 4  334     1610     35       241           138</code></pre>
</div>
</div>
</section>
<section id="consideraçoes-finais" class="level3">
<h3 class="anchored" data-anchor-id="consideraçoes-finais"><strong><em>Consideraçoes Finais</em></strong></h3>
<p>Com base na análise detalhada dos dados apresentados neste relatório, recomendamos ao Sr.&nbsp;João a descontinuação ou venda da Loja 4. A unidade se destaca negativamente por apresentar o menor faturamento entre as quatro lojas do grupo, além de uma tendência consistente de queda nas receitas nos últimos dois anos — um sinal claro de perda de desempenho comercial.</p>
<p>Adicionalmente, a Loja 4 registra o terceiro pior índice de satisfação do cliente, o que sugere possíveis falhas operacionais, de atendimento ou de adequação ao perfil da clientela local. Quando analisamos esses fatores em conjunto — baixo faturamento, tendência de queda e desempenho inferior em satisfação —, a continuidade da operação se mostra pouco vantajosa do ponto de vista estratégico. A venda da loja pode liberar recursos que poderiam ser realocados para fortalecer unidades mais rentáveis ou para expandir a presença da marca em regiões com maior potencial de crescimento.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiada");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiada");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>